version: '3'

services:
  db:
    image: 'postgres:14-alpine'
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"

  prometheus:
    image: 'prom/prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ./src/observability:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  
  grafana:
    image: 'grafana/grafana'
    ports:
      - '5000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=example
    volumes:
      - ./grafana:/var/lib/grafana